lazy val sbtAptly = Project("sbt-aptly", file("."))
  .settings(BaseSettings.defaultSettings: _*)
  .settings(Dependencies.plugin: _*)
  .settings(Testing.defaultSettings: _*)
  .settings(Publish.defaultSettings: _*)
  .settings(Release.defaultSettings: _*)
